#!/usr/bin/python3
import sys
from sys import argv

"""
factors,25th of novembre, 2023
by Judge Kriegelr Lawoko
"""


def factorize(num):

    """
    # Factorizes numbers"""
    a = 2

    if num < 2:
        return
    print()
    print(num, "<- ")
    while num % a:
        a += 1
    print("{:.0f}={:.0f}*{:.0f}".format(num, num / a, a))
    print()
    print(num, "<- ")


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as fil:
        l = fil.readline()

        while l != "":
            num = int(l.split('\n')[0])
            factorize(num)
            l = fil.readline()
except FileNotFoundError:
    print("File not found: %d" % (argv))
except ValueError:
    print("Invalid input in the file: %d" % (argv))
except Exception as ex:
    print("An error occurred: %s" % (str(ex)))
    pass
